#include <bits/stdc++.h>
using namespace std;

using int64 = long long;
using i128 = __int128_t;

struct Vec {
    int64 x, y;
};

int64 gcd_abs(int64 a, int64 b) {
    a = llabs(a);
    b = llabs(b);
    while (b != 0) {
        int64 r = a % b;
        a = b;
        b = r;
    }
    return a;
}

// Returns gcd(|a|, |b|) and coefficients s, t such that s*a + t*b = gcd.
int64 extended_gcd(int64 a, int64 b, int64 &s, int64 &t) {
    if (b == 0) {
        s = (a >= 0 ? 1 : -1);
        t = 0;
        return llabs(a);
    }

    int64 s1, t1;
    int64 g = extended_gcd(b, a % b, s1, t1);
    s = t1;
    t = s1 - (a / b) * t1;
    return g;
}

i128 abs128(i128 x) {
    return x < 0 ? -x : x;
}

i128 gcd128(i128 a, i128 b) {
    a = abs128(a);
    b = abs128(b);
    while (b != 0) {
        i128 r = a % b;
        a = b;
        b = r;
    }
    return a;
}

i128 mod_positive(i128 x, i128 m) {
    x %= m;
    if (x < 0) x += m;
    return x;
}

void print128(i128 x) {
    if (x == 0) {
        cout << "0\n";
        return;
    }

    string result;
    while (x > 0) {
        result.push_back(char('0' + static_cast<int>(x % 10)));
        x /= 10;
    }
    reverse(result.begin(), result.end());
    cout << result << '\n';
}

int main() {
    ios::sync_with_stdio(false);
    cin.tie(nullptr);

    int n;
    cin >> n;

    vector<Vec> portals(n);
    for (Vec &p : portals) {
        cin >> p.x >> p.y;
    }

    // The relevant lattice is generated by all differences between portals.
    //
    // rank 0: no nonzero generator
    // rank 1: generated by lineGenerator
    // rank 2: column-Hermite basis (a, 0), (b, c), where
    //         a > 0, c > 0, and 0 <= b < a.
    int rank = 0;
    Vec lineGenerator{0, 0};

    i128 a = 0;
    i128 b = 0;
    int64 c = 0;

    for (int i = 1; i < n; ++i) {
        Vec v{
            portals[i].x - portals[0].x,
            portals[i].y - portals[0].y
        };

        if (v.x == 0 && v.y == 0) continue;

        if (rank == 0) {
            lineGenerator = v;
            rank = 1;
            continue;
        }

        if (rank == 1) {
            i128 determinant =
                (i128)lineGenerator.x * v.y -
                (i128)lineGenerator.y * v.x;

            if (determinant == 0) {
                int64 coordinateGcd =
                    gcd_abs(lineGenerator.x, lineGenerator.y);

                Vec primitive{
                    lineGenerator.x / coordinateGcd,
                    lineGenerator.y / coordinateGcd
                };

                int64 oldMultiplier, newMultiplier;
                if (primitive.x != 0) {
                    oldMultiplier = lineGenerator.x / primitive.x;
                    newMultiplier = v.x / primitive.x;
                } else {
                    oldMultiplier = lineGenerator.y / primitive.y;
                    newMultiplier = v.y / primitive.y;
                }

                int64 multiplierGcd =
                    gcd_abs(oldMultiplier, newMultiplier);

                lineGenerator = {
                    primitive.x * multiplierGcd,
                    primitive.y * multiplierGcd
                };
                continue;
            }

            int64 s, t;
            c = extended_gcd(lineGenerator.y, v.y, s, t);

            i128 representativeX =
                (i128)s * lineGenerator.x + (i128)t * v.x;

            a = abs128(determinant) / c;
            b = mod_positive(representativeX, a);
            rank = 2;
            continue;
        }

        // Add v to the lattice with current basis (a,0), (b,c).
        // The new lattice index is the gcd of all 2x2 minors.
        i128 currentIndex = a * c;
        i128 minorWithFirstBasis = a * v.y;
        i128 minorWithSecondBasis = b * v.y - (i128)c * v.x;

        i128 newIndex = gcd128(
            currentIndex,
            gcd128(minorWithFirstBasis, minorWithSecondBasis)
        );

        int64 s, t;
        int64 newC = extended_gcd(c, v.y, s, t);

        i128 representativeX = (i128)s * b + (i128)t * v.x;
        i128 newA = newIndex / newC;
        i128 newB = mod_positive(representativeX, newA);

        a = newA;
        b = newB;
        c = newC;
    }

    if (rank < 2) {
        cout << -1 << '\n';
    } else {
        print128(a * c);
    }

    return 0;
}